name: Alps2Qutip (ubuntu) Qutip 4.1

on:
  push:
    branches: [ main ]
  pull_request:
    branches: '**'

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ['3.10']
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install OS dependencies
      run: |
        sudo apt-get update -qq && sudo apt-get install -qq gfortran
    - name: Install Alps2Qutip with full dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install setuptools
        python -m pip install Cython  # Add this line to install Cython	
        pip install qutip==4.1
        pip install pytest
        pip install -e .
    - name: Test Alps2Qutip
      run: |
        ALPSQUTIP_ALLTESTS=1 python -m pytest test